### ISSUE TITLE
Request: Change Player and Self Name Color in Chat

### ISSUE THREAD

**Issue by dblack850** [Caraxi/SimpleTweaksPlugin#19]
Been wanting this, as some WoW addons add this functionality and I feel like both would improve RP and standard communication.

1) The ability to make other players' names a different color than the rest of chat so that the names stand out.

2) Similarly, the ability to have a specified color for one's own name so that you can easily recognize when someone is calling for you or speaking about you.

I'm not sure if this is possible or if this is the right place to request these tweaks but I'm giving it a shot!

**Comment by TeleTabs** [comment]
It would be nice to automatically add friends and fc (fc equals green = group/alianca/normal green name)

**Comment by jjspace** [comment]
So the ability to change _other_ players names in chat was added at some point which is rather helpful in busy spaces. But it's not possible to change your _own_ name so it's easier to spot your own messages. I have a wiled guess this is due to the way it's parsing the chat looking for a combination of a Character name _and_ server name which your own name does not have? Regardless I'd really like to be able to...

**Comment by Caraxi** [comment]
Its related to being able to click other peoples names and not your own, unfortunately its much less simple to do, but if you want it you can manually do it with Chat Alerts
