### ISSUE TITLE
[Bug] Large Cooldown Timers Not Displayed on Cross Hotbar when Expanded Hold is Used

### ISSUE THREAD

**Issue by wexxlee** [Caraxi/SimpleTweaksPlugin#260]
Large cooldown timers are not displaying on cross hotbars when those hotbars are displayed using Expanded Hold controls in game.

Repro steps:
1. Add a skill (Swiftcast in this case) to Hotbar 1 or Cross Hotbar 1.
2.  Add the same skill to Cross Hotbar 3 (Right)
3.  In Character Config-> Hotbar Settings -> Custom, turn on "Enable expanded hold controls with LT + RT" and set both display options to "Cross Hotbar 3 - Right.
4.  Use the skill in game.
5.  The skill will display the large cooldown on Hotbar 1 or Cross Hotbar 1.  If you hold down LT and RT though to display the expanded hold controls, the skill displays with only the standard in-game cooldown timer.

Example screenshot attached
![lcd2](https://user-images.githubusercontent.com/86693821/158041395-bcb4b33b-29d1-4a13-8438-1f806c2b0f02.png)
.

**Comment by ItsBexy** [comment]
Peeking into this, the core issue (and the reason the Tweak opts to just skip over EXHB icons) is the fact that Expanded Hold Controls use the middle eight slots of the Cross Hotbar (4-11), but populate those slots with either the first eight buttons (0-7) or the last eight buttons (8-15) from the bar mapped to it in Character Config.

So essentially, that means whenever an EXHB icon is being updated, the relevant action that needs to be referenced is actually 4 slots ahead/behind on a different bar.

To fix this, the line of code in LargeCooldownCounter.cs that would need adjustment is here: (line 127)

`var slotStruct = hotbarModule->HotBar[ab->HotbarID]->Slot[i];`

And the steps for the fix would be:

1. Check it's an EXHB input, and if it's a visible EXHB slot (4 <= i <= 11). Otherwise, proceed or skip as normal.
2. Check whether it's an LTRT or RTLT input
3. Check the character config setting to identify which bar is mapped to that input, and which side of said bar (left/right)
4. replace `ab->HotbarID` with the ID of that bar
5. Use `Slot[i-4]` if left side, and `Slot[i+4]` if right side

I haven't sorted out the step of retrieving that character config setting yet, but a tentative test where I just hardcoded in 12 (cross hotbar 3, which is my own setting) as the hotbar ID, alongside the other steps, got it to work.

![ffxiv_04302022_145113_943](https://user-images.githubusercontent.com/103910869/166122314-dc45b284-e503-40db-a9d1-48feae7ae9d9.png)

**Comment by Caraxi** [comment]
Fixed in next version thanks to ItsBexy
