### ISSUE TITLE
Bug in "Examine" cursor movement when [Adjust Equipment Positions] is enabled.

### ISSUE THREAD

**Issue by torakiti2017** [Caraxi/SimpleTweaksPlugin#301]
The cursor movement in "Examine" is as follows.

"Search Comment"
(Cursor up/down)
"Main arm"
(Cursor up/down)
"Grand Company Rank"
(Cursor up/down)
"Head Equipment"

**Comment by ryankhart** [comment]
Oh, good catch. This seems definitely related to update that resolved this issue https://github.com/Caraxi/SimpleTweaksPlugin/issues/295.

**Comment by ryankhart** [comment]
I tried for a solid 2 hours to reverse engineer https://github.com/Caraxi/SimpleTweaksPlugin/commit/4bce10cf99ca991a4d3e656f0bbd9c66b3c7501f to make it work for the Examine window to do a pull request, but it's making my brain hurt now. lol

I think my issue is I have no idea where to find the numbers that are being used for the various enums. They seemed arbitrary at first, but then I saw that they get feed right back into `ControllerInputDetour` which goes into a hook, which I don't know how that works. Even the Dalamud API documentation assumes you know what a hook is, so that's not useful to me.

I'll just wait for a commit that fixes this, and piece together my knowledge that way. I learn best from trying first, then looking at example code.

**Comment by Aireil** [comment]
The Node enum contains the indices of the different collision nodes in the collision list of the Character addon.
It's not documented anywhere, as this is a bit more advanced / RE territory.

If you want to play around with UI nodes: /tweaks Debug => UI Debugging

**Comment by ryankhart** [comment]
Whoa! `/tweaks Debug` just opened my eyes to a whole new world with this. No wonder this plugin has so many contributors building their own tweaks on top of this.

**Comment by ryankhart** [comment]
Heads up, I have a fix for this issue working now. I'm just noticing that I have a bunch of other commits in my PR that mirror the code on this repository that I'm trying to figure out how to get rid of. I'm still a beginner with a lot of git fringe cases like these. It'll still work if I submit the PR now, but it'll clutter up the commit list here. :-/

**Comment by torakiti2017** [comment]
Thank you for attempting to fix it.
I am a PAD user and it really helps.
