### ISSUE TITLE
[Bug] Fade Unavailable Actions functions differently from KitchenSync

### ISSUE THREAD

**Issue by athuy** [Caraxi/SimpleTweaksPlugin#495]
The tweak makes all skills transparent if they cannot be immediately used instead of transparent only when unavailable due to level sync. This includes being on cooldown, not having enough MP/job specific resource/simply being unusable due to combo requirements. 

If this is the intended use, KitchenSync should not be considered deprecated as it is functionally different.

**Comment by Cloud7050** [comment]
Indeed! It would be great if this tweak could function more like the now-deprecated KitchenSync it's replacing, as the above differentiation is extremely valuable. An action being unusable temporarily, for example due to not meeting resource requirements yet, affects how you fight very differently to an action that will be unavailable for the entire fight, be it due to level sync, not being unlocked etc.

The additional configuration options that KitchenSync had, such as toggling fading for macros or selecting only specific hotbars, would also be much appreciated. For example, with the former enabled and the latter in use, they prevented my generic rez macro that's on another hotbar from ever being unintentionally faded out, even if I'm on a job that uses a rez with a different micon.

An example of the difference in functionality:

![image](https://user-images.githubusercontent.com/44526554/223633503-1d78536c-ec37-44ec-a4e0-ba30fb3465e8.png)

Above is how KitchenSync works. "Apply to Macros" is enabled, but the smaller hotbar that my generic rez macro is on is not selected in the settings. The plugin keeps Confiteor and Sheltron merely darkened like in vanilla, due to not having Confiteor Ready and enough Oath Gauge respectively. Once I have those resources, they'll appear normal and I'll be able to use them. Meanwhile, I don't have Clemency unlocked at all, so I'll never be able to use it, thus the plugin fades it out. Since my rez macro is not on a selected hotbar, it also isn't faded out.

![image](https://user-images.githubusercontent.com/44526554/223634216-2c06fe7e-141b-4b8f-b43d-e17d43842aee.png)

Above is how the new tweak works. Anything that isn't usable right this instant is faded. If it would be darkened in vanilla, it is instead faded. While this fits the tweak's description, the greatly simplified functionality is not able to take KitchenSync's place.

**Comment by Cloud7050** [comment]
Tagging @MidoriKami. And of course, thanks to all the devs for the work that you do!

**Comment by Krojack** [comment]
Nice, didn't have to start my own thread about this.

I like how I could remove one plugin and this being added to simple tweaks but I don't like how it fades abilities that are on cooldown.  I literally can't see how close something like Lucid Dreaming is to being ready.

Maybe add a checkbox option to also fade abilities on cooldown for those that also want that.

For the time being I went back to KitchenSynk.

**Comment by MidoriKami** [comment]
I have been berated over this CONSTANTLY since I announced the move to SimpleTweaks.

I have already implemented these features #493 please stop harassing me over this.
I have been harassed over KitchenSync constantly for the last 24 hours.
I am free to do what I want with my plugins. You are enjoying a free service provided by voulenteers.

**Comment by MidoriKami** [comment]
I had intended to take my time to figure out how to re-implement the KitchenSync behavior in the tweak, which is why I allow people to keep using KitchenSync until 6.38.

However due to the CONSTANT harassment over this, I was forced to spend time I frankly did not have to implement these features.

**Comment by Krojack** [comment]
I'm sorry if you took my comment as harassment. I was simply giving my personal input and nothing more.

Anyone who harassed you over this are scum.

**Comment by Cloud7050** [comment]
I'm sorry to learn of your frustrations. I am not a stranger to volunteer dev work and being approached to do what others would like to see. I'm unsure which channel(s) you were harassed through, but I think any sensible player would appreciate whatever they're getting, understanding that they aren't owed anything and that all the devs have to put their "real" lives first. Outside of that, there will be bad apples in any community, and I would try not to take it too personally or stress over it. After all, we each have our own reasons for developing, and crunching to the point of losing that drive and enjoyment would be a shame. Some people need to be given a firm "no" or "not now", and yes, they have the option to do it themselves as it were, should they feel so strongly about something.

I'd surmise that seeing this issue was the last straw, and a public outlet to let people know your thoughts - an announcement of sorts that the feedback has already been noted (and, thankfully, implemented). As KitchenSync opens a window with every game start notifying players of the deprecation / limited lifespan and urging them to make the switch, perhaps a sentence or two noting that the difference in functionality was known and already planned to be addressed somewhere down the line would have helped avert this. That the intended usage, should players prefer, was to still stay on KitchenSync till such time as said functionality could be re-implemented (which is what I'm doing as well).

Thanks again. Know that what you do is appreciated by many and enhances the experience of more still.

**Comment by MidoriKami** [comment]
This can also be closed, this behavior was added to the Fade Unavailable Actions Tweak.
