### ISSUE TITLE
chdir doesn't do anything

### ISSUE THREAD

**Issue by Endracion** [Caraxi/SimpleTweaksPlugin#5]
Is this supposed to open a Windows Explorer window with the character's directory under My Documents/My Games/Final Fantasy XIV/Character ID?

It doesn't seem to do anything for me - I'm running QQTabBar extension which adds tabs to Windows Explorer and remembers my open folders, but as far as I know it doesn't change its regular functions, all sorts of other apps are able to open new windows.

**Comment by Caraxi** [comment]
It works fine with normal explorer using `/chrdir open`. In theory there should be no differences with working with a modified explorer since its just opening a folder, but who knows. If the issue is persisting can you please check the `dalamud.txt` log to see if theres any errors after using the `/chrdir open` command.

**Comment by Endracion** [comment]
Small update - `/chdir open` does work, but `/chdir` alone, or `/savedir` alone don't print the path in chat, as suggested by the help text.

**Comment by Caraxi** [comment]
oh... thats a typo...

`/chrdir` prints the directly to chat
`/chrdir open` opens it in explorer

`/savedir` isn't a command and I have no idea how I typed that lol

**Comment by Endracion** [comment]
Ah well that explains it haha - all is well except the random savedir then.
I guess you could modify it to send to the screenshot directory if you'd like?

Thanks for the help.
