### ISSUE TITLE
[Feature Request] Auto renew Instant-Portraits

### ISSUE THREAD

**Issue by Dovahderp1** [Caraxi/SimpleTweaksPlugin#716]
Hey Devs, is it possible to add a tweak that renews your instant portrait as soon as the gear set is updated?

**Comment by Caraxi** [comment]
Not going to happen sorry

**Comment by Dovahderp1** [comment]
Alright. Thanks for the consideration Caraxi!

**Comment by Fabricio20** [comment]
Hey hey @Caraxi , is there any chance this could be reconsidered? I think since this issue was initially made they've added the pop-up to confirm instant portrait update when you swap (with the funny checkbox that doesn't do what you want), maybe make it so simple tweaks just confirms that pop-up?

To be clear, the checkbox just stops the pop-up from appearing, but does not auto-update the portrait.

![Image](https://github.com/user-attachments/assets/b2790e2a-2753-4402-b43a-b2e88a3f422e)
